"""Change User ID to UUID

Revision ID: 8205ed7f841d
Revises: 3d9f9c200a56
Create Date: 2026-04-01 16:29:59.881690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8205ed7f841d'
down_revision: Union[str, None] = '3d9f9c200a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop primary key constraint and column
    op.drop_column('user', 'id')
    # Add new UUID column as primary key
    op.add_column('user', sa.Column('id', sa.UUID(as_uuid=True), primary_key=True, index=True, nullable=False, server_default=sa.text('gen_random_uuid()')))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
